//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallengeOfEldersModifier
    {
        public int id { get; set; }
        public Nullable<int> challengeofeldersid { get; set; }
        public Nullable<int> modifierid { get; set; }
    
        public virtual ChallengeOfElder CoE { get; set; }
        public virtual Modifier Modifier { get; set; }
    }
}
