//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryItem()
        {
            this.bountydays = new HashSet<BountyDay>();
            this.xurdays = new HashSet<XurDay>();
            this.weeklyheroicmissionrewards = new HashSet<WeeklyHeroicMissionReward>();
            this.nightfallmissionrewards = new HashSet<NightfallMissionReward>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string icon { get; set; }
        public string rarity { get; set; }
        public string type { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> rarityid { get; set; }
        public Nullable<int> quality { get; set; }
        public string friendlyname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BountyDay> bountydays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XurDay> xurdays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeeklyHeroicMissionReward> weeklyheroicmissionrewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NightfallMissionReward> nightfallmissionrewards { get; set; }
    }
}
