//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryItem()
        {
            this.BountyDays = new HashSet<BountyDay>();
            this.XurDays = new HashSet<XurDay>();
            this.WeeklyHeroicMissionRewards = new HashSet<WeeklyHeroicMissionReward>();
            this.NightfallMissionRewards = new HashSet<NightfallMissionReward>();
            this.rewardsdays = new HashSet<RewardsDay>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string icon { get; set; }
        public string rarity { get; set; }
        public string type { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> rarityid { get; set; }
        public Nullable<int> quality { get; set; }
        public string friendlyname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BountyDay> BountyDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XurDay> XurDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeeklyHeroicMissionReward> WeeklyHeroicMissionRewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NightfallMissionReward> NightfallMissionRewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RewardsDay> rewardsdays { get; set; }
    }
}
