//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManifestActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManifestActivity()
        {
            this.ChallengeOfElders = new HashSet<ChallengeOfElder>();
            this.CrucibleDailyDays = new HashSet<CrucibleDailyDay>();
            this.Nightfalls = new HashSet<Nightfall>();
            this.ManifestRewards = new HashSet<ManifestReward>();
            this.ManifestSkulls = new HashSet<ManifestSkull>();
            this.PrisonOfElders = new HashSet<PrisonOfElder>();
            this.HeroicDailyDays = new HashSet<HeroicDailyDay>();
            this.WeeklyHeroics = new HashSet<WeeklyHeroic>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string icon { get; set; }
        public string pgcricon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChallengeOfElder> ChallengeOfElders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrucibleDailyDay> CrucibleDailyDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nightfall> Nightfalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManifestReward> ManifestRewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManifestSkull> ManifestSkulls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrisonOfElder> PrisonOfElders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeroicDailyDay> HeroicDailyDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeeklyHeroic> WeeklyHeroics { get; set; }
    }
}
