//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrisonOfEldersRound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrisonOfEldersRound()
        {
            this.prisonofeldersmodifiers = new HashSet<PrisonOfEldersModifier>();
            this.prisonofeldersraces = new HashSet<PrisonOfEldersRace>();
        }
    
        public int id { get; set; }
        public Nullable<int> prisonofeldersid { get; set; }
        public Nullable<int> round { get; set; }
    
        public virtual PrisonOfElder prisonofelder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrisonOfEldersModifier> prisonofeldersmodifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrisonOfEldersRace> prisonofeldersraces { get; set; }
    }
}
