//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrisonOfEldersRace
    {
        public int id { get; set; }
        public Nullable<int> levelid { get; set; }
        public Nullable<int> raceid { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual PrisonOfEldersRound Round { get; set; }
    }
}
