//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL.Destiny2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DestinyDaily2Entities : DbContext
    {
        public DestinyDaily2Entities()
            : base("name=DestinyDaily2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InventoryEmblem> InventoryEmblems { get; set; }
        public virtual DbSet<InventorySparrow> InventorySparrows { get; set; }
        public virtual DbSet<InventoryShip> InventoryShips { get; set; }
        public virtual DbSet<D2Nightfall> D2Nightfalls { get; set; }
        public virtual DbSet<D2NightfallModifier> D2NightfallModifiers { get; set; }
        public virtual DbSet<ClassifiedOverride> ClassifiedOverrides { get; set; }
        public virtual DbSet<D2NightfallChallenge> D2NightfallChallenges { get; set; }
    }
}
