//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL.Destiny1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallengeOfEldersRound
    {
        public int id { get; set; }
        public Nullable<int> eldersid { get; set; }
        public Nullable<long> combatantid { get; set; }
    
        public virtual ChallengeOfElder CoE { get; set; }
        public virtual Combatant Combatant { get; set; }
    }
}
