//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL.Destiny1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DestinySqlEntities : DbContext
    {
        public DestinySqlEntities()
            : base("name=DestinySqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BountyDay> BountyDays { get; set; }
        public virtual DbSet<ChallengeOfElder> ChallengeOfElders { get; set; }
        public virtual DbSet<ChallengeOfEldersModifier> ChallengeOfEldersModifiers { get; set; }
        public virtual DbSet<ChallengeOfEldersRound> ChallengeOfEldersRounds { get; set; }
        public virtual DbSet<ChallengeOfEldersScoreModifier> ChallengeOfEldersScoreModifiers { get; set; }
        public virtual DbSet<Combatant> Combatants { get; set; }
        public virtual DbSet<CrucibleDailyDay> CrucibleDailyDays { get; set; }
        public virtual DbSet<HeroicDailyDay> HeroicDailyDays { get; set; }
        public virtual DbSet<InventoryItem> InventoryItems { get; set; }
        public virtual DbSet<ManifestActivity> ManifestActivities { get; set; }
        public virtual DbSet<ManifestReward> ManifestRewards { get; set; }
        public virtual DbSet<ManifestSkull> ManifestSkulls { get; set; }
        public virtual DbSet<Modifier> Modifiers { get; set; }
        public virtual DbSet<Nightfall> Nightfalls { get; set; }
        public virtual DbSet<NightfallMissionModifier> NightfallMissionModifiers { get; set; }
        public virtual DbSet<NightfallMissionReward> NightfallMissionRewards { get; set; }
        public virtual DbSet<PrisonOfElder> PrisonOfElders { get; set; }
        public virtual DbSet<PrisonOfEldersModifier> PrisonOfEldersModifiers { get; set; }
        public virtual DbSet<PrisonOfEldersRace> PrisonOfEldersRaces { get; set; }
        public virtual DbSet<PrisonOfEldersRound> PrisonOfEldersRounds { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<ScoreModifier> ScoreModifiers { get; set; }
        public virtual DbSet<WeeklyHeroic> WeeklyHeroics { get; set; }
        public virtual DbSet<WeeklyHeroicMissionReward> WeeklyHeroicMissionRewards { get; set; }
        public virtual DbSet<WeeklyHeroicModifier> WeeklyHeroicModifiers { get; set; }
        public virtual DbSet<XurD1Day> XurD1Days { get; set; }
        public virtual DbSet<MaterialExchange> MaterialExchanges { get; set; }
        public virtual DbSet<RaidChallenge> RaidChallenges { get; set; }
        public virtual DbSet<RaidChallengeDay> RaidChallengeDays { get; set; }
        public virtual DbSet<CrucibleWeeklyDay> CrucibleWeeklyDays { get; set; }
        public virtual DbSet<XurLocation> XurLocations { get; set; }
        public virtual DbSet<XurD1LocationDay> XurD1LocationDays { get; set; }
        public virtual DbSet<TrialsMapDay> TrialsMapDays { get; set; }
        public virtual DbSet<RewardsDay> RewardsDays { get; set; }
        public virtual DbSet<FeaturedRaid> FeaturedRaids { get; set; }
        public virtual DbSet<FeaturedRaidDay> FeaturedRaidDays { get; set; }
        public virtual DbSet<FeaturedRaidChallenge> FeaturedRaidChallenges { get; set; }
        public virtual DbSet<WeeklyFeatured> WeeklyFeatureds { get; set; }
        public virtual DbSet<WeeklyFeaturedModifier> WeeklyFeaturedModifiers { get; set; }
        public virtual DbSet<WeeklyFeaturedReward> WeeklyFeaturedRewards { get; set; }
    }
}
