//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL.Destiny1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeaturedRaid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeaturedRaid()
        {
            this.featuredraiddays = new HashSet<FeaturedRaidDay>();
            this.featuredraidchallenges = new HashSet<FeaturedRaidChallenge>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string imageurl { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeaturedRaidDay> featuredraiddays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeaturedRaidChallenge> featuredraidchallenges { get; set; }
    }
}
