//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyDailyDAL.Destiny1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyFeaturedModifier
    {
        public int id { get; set; }
        public Nullable<int> weeklyfeaturedid { get; set; }
        public Nullable<int> modifierid { get; set; }
    
        public virtual Modifier modifier { get; set; }
        public virtual WeeklyFeatured weeklyfeatured { get; set; }
    }
}
